import { useEffect, useRef } from 'react';
import { useDispatch } from 'react-redux';
import { addAlert } from '../store/alertsSlice';
import { supabase } from '../services/supabaseClient';

const SIMULATED_KEYWORDS = ['emergency', 'வலிக்குது', 'help me', 'silence', 'background', '救命'];
const SIMULATED_LANGUAGES = ['English', 'Tamil', 'Hokkien', 'Mandarin', 'Malay', 'Teochew'];
const LOCATIONS = [
  'Blk 123 #11-20, Bedok', 
  'Blk 456 #02-14, Tampines', 
  'Blk 789 #15-05, Yishun', 
  'Blk 234 #04-44, Jurong East'
];

/**
 * Custom hook managing the data layer for Live incoming alerts via Supabase.
 * Falls back to local generated mock generator if .env isn't configured.
 */
export default function useAlertWebSocket() {
  const dispatch = useDispatch();
  const mockTimerRef = useRef(null);

  useEffect(() => {
    
    // --- SUPABASE REALTIME SDK PATH (PHASE 6) ---
    /*
    // Built on WebSockets natively, but drastically simplifies the connection process.
    // We "subscribe" to the 'cases' table.  case_events creates the case.
    if (supabase) {
      console.log('[useAlertWebSocket] Connecting to Supabase Realtime <cases> table...');
      
      const channel = supabase
        .channel('public-cases-inserts')
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'cases' }, async (payload) => {
          console.log('[useAlertWebSocket] New case spawned:', payload.new);
          
          // 1. We just received the raw 'cases' row.
          const rawCase = payload.new;
          
          // 2. The cases table holds beneficiary_id. We fetch the matching pab_beneficiaries row.
          const { data: beneficiaryData } = await supabase
            .from('pab_beneficiaries')
            .select('*')
            .eq('beneficiary_id', rawCase.beneficiary_id)
            .single();
          
          // 3. Re-map the raw Supabase logic into the Redux State schema our UI expects.
          const newAlert = { 
            id: rawCase.case_id, 
            tier: rawCase.urgency_bucket || 'low', // e.g., 'urgent', 'med', 'low'
            source: rawCase.source || 'btn',
            timeAgo: 0,
            timestamp: rawCase.opened_at || rawCase.created_at,
            actionState: rawCase.status || 'new', // new, in_progress, resolved
            // Add other fields from triage_flags_json or payload_json here
            
            // Inject the merged beneficiary:
            beneficiary: beneficiaryData
          };
          
          dispatch(addAlert(newAlert));
        })
        .subscribe();
        
      return () => {
         console.log('[useAlertWebSocket] Disconnecting from Supabase');
         supabase.removeChannel(channel);
      }
    }
    */

    // --- STANDARD BACKEND REST API SKELETON ---
    /*
    // This function fetches existing cases from your Backend server.
    // It should be called once on dashboard mount to load the backlog.
    const fetchActiveCases = async () => {
      try {
        // e.g., calling your node/python backend that queries Supabase for us
        const response = await fetch('https://api.yourbackend.com/v1/cases?status=in(new,in_progress)');
        const apiData = await response.json();
        
        // Loop through the array of unresolved cases and pump them into Redux
        // apiData.cases.forEach(c => {
        //    dispatch(addAlert({ id: c.case_id, tier: c.urgency_bucket, beneficiary: c.beneficiary_data ... }))
        // });
      } catch (err) {
        console.error('Failed to fetch initial cases pipeline', err);
      }
    };
    // fetchActiveCases();
    */
    
    // --- MOCK FALLBACK PATH ---
    // if (!supabase) {
      console.log('[useAlertWebSocket] Supabase not connected. Using local mock simulation.');
      
      const emitMockMessage = () => {
        const isUrgent = Math.random() > 0.7; // 30% chance of urgent
        
        const newAlert = {
          id: Math.floor(Math.random() * 900) + 100 + '',
          tier: isUrgent ? 'urgent' : (Math.random() > 0.5 ? 'med' : 'low'),
          source: Math.random() > 0.5 ? 'audio' : 'btn',
          keywords: [SIMULATED_KEYWORDS[Math.floor(Math.random() * SIMULATED_KEYWORDS.length)]],
          languages: [SIMULATED_LANGUAGES[Math.floor(Math.random() * SIMULATED_LANGUAGES.length)]],
          location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)],
          coordinates: `${(Math.random() * 0.1 + 1.3).toFixed(4)}°N, ${(Math.random() * 0.1 + 103.8).toFixed(4)}°E`,
          pitch: Math.floor(Math.random() * 100),
          timeAgo: 0,
          timestamp: new Date().toISOString(),
          actionState: 'new', // always spawns as new
          metadata: {
            mlSource: isUrgent ? 'Audio ML detection' : 'Keyword match',
            pitchScoreDetail: 'Pitch score generated by Mock WebSocket.',
            dialectDetected: 'Multiple',
            falsePositiveAnalysis: {
              extraClicks: { passed: Math.random() > 0.2, desc: 'Single press verified' },
              backgroundNoise: { passed: Math.random() > 0.3, desc: 'Signal above noise floor' },
              silentAudio: { passed: !isUrgent, desc: 'Audio active' } // fail it if urgent to test UI
            }
          },
          beneficiary: {
            nric: `S${Math.floor(Math.random() * 9000000) + 1000000}A`,
            full_name: ['Tan Ah Kow', 'Lim Mei Ling', 'Siti Binte Omar', 'Muthu Kumar'][Math.floor(Math.random() * 4)],
            age: Math.floor(Math.random() * 25) + 65,
            phone_number: `+65 ${Math.floor(Math.random() * 90000000) + 80000000}`,
            emergency_contact_name: ['Shirley Tan', 'David Lim', 'Ali Bin Hassan', 'Priya Kumar'][Math.floor(Math.random() * 4)],
            emergency_contact: `+65 ${Math.floor(Math.random() * 90000000) + 80000000}`,
            patient_medical_summary: isUrgent ? 'History of ischemic heart disease and recurrent falls.' : 'Hypertension, Type 2 Diabetes.',
            DNR_status: Math.random() > 0.8 ? 'ACTIVE' : 'NONE',
            primary_language: 'English',
            insurance_ward_class: Math.random() > 0.5 ? 'A1' : 'B2',
            primary_hospital: ['Singapore General Hospital', 'Tan Tock Seng Hospital', 'Changi General Hospital'][Math.floor(Math.random() * 3)]
          }
        };
        
        dispatch(addAlert(newAlert));
        
        mockTimerRef.current = setTimeout(emitMockMessage, Math.random() * 10000 + 15000); 
      };

      mockTimerRef.current = setTimeout(emitMockMessage, 5000); // Start first one in 5s

      return () => {
        if (mockTimerRef.current) clearTimeout(mockTimerRef.current);
      }
    // }
  }, [dispatch]);

}
